# These are the sponsors for these mods


custom: ['https://www.youtube.com/channel/UCYAR8uvGRjiMMB-LSYPkO0Q', 'https://www.youtube.com/MostlyGhostlyGamingOfficial', 'https://www.youtube.com/LagonGaming', 'https://www.youtube.com/TheWolfepup06']
